### ISSUE TITLE
`attribute_not_exists` doesn't seem to be working.  Able to insert the same key.

### ISSUE THREAD

**Issue by dhang-sc** [guregu/dynamo#236]
Am i doing something wrong?  I ran this locally, and expected an error when it tries to insert the same `UserID`. But it didn't do anything.  This is pretty much what I see from the PutTest

Any advice appreciated it?

![image](https://github.com/guregu/dynamo/assets/158533208/bd5c5ef1-2a2a-4c99-bf3b-0b2bb8a0f503)

```
package main

import (
	"time"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/credentials"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/guregu/dynamo"
	"github.com/rs/zerolog/log"
)

// Use struct tags much like the standard JSON library,
// you can embed anonymous structs too!
type widget struct {
	UserID int       `dynamo:"UserID,hash"`
	Time   time.Time `dynamo:"Time,range"`

	Msg string `dynamo:"Message"` // Change name in the database
}

func main() {
	awsConfig := &aws.Config{}
	region := "us-east-1"

	awsConfig = awsConfig.
		WithRegion(region).
		WithEndpoint("http://localhost:8000").
		WithCredentials(credentials.NewStaticCredentials("test", "test", "test")).
		WithCredentialsChainVerboseErrors(true)

	sess := session.Must(session.NewSession(awsConfig))
	db := dynamo.New(sess)
	if err := db.CreateTable("Widgets", widget{}).Run(); err != nil {
		//panic(err)
	}
	table := db.Table("Widgets")

	// put item
	w := widget{UserID: 613, Time: time.Now(), Msg: "hello"}
	err := table.Put(w).If("attribute_not_exists(UserID)").Run()
	if err != nil {
		log.Printf("%v", err)
		return
	}
}

```

Version: `github.com/guregu/dynamo v1.23.0`

I'm using the following to start up dynamo locally with `docker-compse up`
```
version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:2.4.0"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
```
